# Generated by Django 4.2.11 on 2024-03-08 06:02

import pathlib

import django.core.files.storage
import django.core.validators
import django.utils.timezone
from django.db import migrations, models

import utils.files


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("date_deleted", models.DateTimeField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location=pathlib.PureWindowsPath("D:/RosterPulse/src")
                        ),
                        upload_to=utils.files.RenameFile(
                            "files/attendance/{instance.roster_user_schedule.user_id}/{instance.date_created}.{extension}"
                        ),
                        validators=[
                            utils.files.ValidateFileSize(max_file_size=5),
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=("jpeg", "png", "jpg")
                            ),
                        ],
                    ),
                ),
                (
                    "attendance_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendance",
            },
        ),
    ]
