# Generated by Django 4.2.11 on 2024-03-08 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rosters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="roster_user_schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="rosters.rosteruserschedule",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
